apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    repository: https://charts.longhorn.io/longhorn
    name: podinfo
    version: 1.2.3
