apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    releaseName: longhorn
    spec:
      chart: https://charts.longhorn.io/longhorn
      version: 1.2.3
