- include_tasks: ./prepare-host.yml
- include_tasks: ./install-k3s.yml

# TODO: setup loadbalancer?

- include_tasks: ./start-k3s-control-nodes.yml
  # TODO: probably need some output here?

- include_tasks: ./start-k3s-agents.yml
  # TODO: probably need the output from control nodes
