- name: provision Arch Linux hosts
  hosts: all
  gather_facts: yes
  roles:
    - role: xanmanning.k3s

# - hosts: k3s_nodes
#   vars:
#     k3s_registration_address: loadbalancer  # Typically a load balancer.
#     k3s_server:
#       datastore-endpoint: "postgres://postgres:verybadpass@database:5432/postgres?sslmode=disable"
#   pre_tasks:
#     - name: Set each node to be a control node
#       ansible.builtin.set_fact:
#         k3s_control_node: true
#       when: inventory_hostname in ['node2', 'node3']
#   roles:
#     - role: xanmanning.k3s
