---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - configmap.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
patchesStrategicMerge:
  - namespace.yaml
